
services:
  app:
    image: fizzbuzz2/portal-checker:v2.0.0
    ports:
      - "5001:5000"
    build:
      platforms:
        - linux/amd64
        - linux/arm64
      context: . 
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development