
services:
  portal-checker:
    container_name: portal-checker
    hostname: portal-checker
    # image: fizzbuzz2/portal-checker:8a14a99
    ports:
      - "5002:5000"
    build:
      platforms:
        # - linux/amd64
        - linux/arm64
      context: . 
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - EXCLUDED_URLS_FILE=excluded-urls.yaml
      - URLS_FILE=urls.yaml