version: '3'

tasks:
  build:
    desc: Build Docker image
    cmds:
    - docker compose build --push

  run:
    desc: Run
    cmds:
    - docker compose up -d

  shell:
    desc: Run shell
    cmds:
    - pipenv shell

  run-dev:
    desc: Run
    cmds:
    - flask run

  helm-template:
    desc: template helm chart
    cmds:
    - helm template ./helm

default:
  desc: List available tasks
  cmds:
  - task --list
