version: '3'

vars:
  IMAGE_NAME: fizzbuzz2/portal-checker:v1.7.2

tasks:
  build:
    desc: Build Docker image
    cmds:
    - docker compose build --push

  run-dev:
    desc: Run
    cmds:
    - flask run

  helm-template:
    desc: template helm chart
    cmds:
    - helm template ./helm

default:
  desc: List available tasks
  cmds:
  - task --list
