# Role definition (e.g., ingress-reader-role.yaml)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "application.fullname" . }}-cluster-role
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", ]
  verbs: ["get", "list"]
# add httproute
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["httproutes", ]
  verbs: ["get", "list"]
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["gateways", ]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["namespaces", ]
  verbs: ["get", "list"]
---
# Role binding definition (e.g., ingress-reader-binding.yaml)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "application.fullname" . }}-binding
subjects:
- kind: ServiceAccount
  name: portal-checker
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "application.fullname" . }}-cluster-role
  apiGroup: rbac.authorization.k8s.io
