# Role definition (e.g., ingress-reader-role.yaml)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: portal-checker-role
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", ]
  verbs: ["get", "list"]
---
# Role binding definition (e.g., ingress-reader-binding.yaml)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-reader-binding
subjects:
- kind: ServiceAccount
  name: portal-checker
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: portal-checker-role
  apiGroup: rbac.authorization.k8s.io
