# helm/templates/cert-secret.yaml
{{ if .Values.certificate.enabled }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ template "application.fullname" . }}-cert
    labels: {{- include "application.labels" . | nindent 4 }}
type: Opaque
data:
    cert.crt: {{ .Files.Get "certs/cert.crt" | b64enc | default ""}}

{{ end }}