{{- if not .Values.autoswagger.disablePresidio }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "application.fullname" . }}-spacy-models
  labels: {{- include "application.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.presidio.storageSize }}
  {{- if .Values.presidio.storageClass }}
  storageClassName: {{ .Values.presidio.storageClass }}
  {{- end }}
{{- end }}