# Docker-specific values for branch deployments
# This file is automatically updated by GitHub Actions

image:
  repository: fizzbuzz2/portal-checker
  tag: "2.8.1-feat-perf-f61c328"
  pullPolicy: Always

# Environment for branch testing
env:
  - name: FLASK_ENV
    value: "development"
  - name: LOG_LEVEL
    value: "DEBUG"
  - name: PORT
    value: "5000"
  - name: MAX_CONCURRENT_REQUESTS
    value: "5"
  - name: REQUEST_TIMEOUT
    value: "3"
  - name: CACHE_TTL_SECONDS
    value: "300"
  - name: KUBERNETES_POLL_INTERVAL
    value: "600"
  - name: CHECK_INTERVAL
    value: "30"
  - name: URLS_FILE
    value: "/app/data/urls.yaml"
  - name: EXCLUDED_URLS_FILE
    value: "/app/config/excluded-urls.yaml"

# Branch-specific annotations
podAnnotations:
  git.branch: "feat/perf"
  git.commit: "f61c328"
  build.timestamp: "2025-07-02T10:30:00Z"
  environment: "development"

# Development-specific resource limits
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi