
services:
    app:
      ports:
        - "5000:5000"
      build:
        platforms:
          - linux/amd64
          - linux/arm64
        context: . # docker-compose.yml in current directory
      environment:
        - FLASK_APP=app.py
        - FLASK_ENV=development