name: build

on:
  push:
    branches:
    - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_KEY: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: portal-checker

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_KEY }}

    - name: Build Docker image
      run: 
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

    - name: Push Docker image
      run: docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Update values.yaml with last image tag
      run: "cd helm\n sed -i 's|tag:.*|tag: '${{ github.sha }}'|' values.yaml \ngit config --global user.name 'GitHub Actions'\ngit config --global user.email 'actions@github.com'\ngit add values.yaml\ngit commit -m \"Update image tag with ${{ github.sha }}\"\ngit push\n"
