name: Build and Update Helm Values

on:
  push:
    branches:
      - main  # adjust this to your branch

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # needed for pushing changes
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # This ensures we have the full git history
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          # Adjust these based on your registry
          registry: your-registry.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Get short SHA
        id: sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: fizzbuzz2/portal-checker:${{ steps.sha.outputs.SHORT_SHA }}
          context: .  # adjust if your Dockerfile is in a different directory
      
      - name: Update Helm values
        run: |
          # Assuming your values.yaml is in helm/values.yaml
          # Replace 'image.tag' with the new SHA
          yq e -i '.image.tag = "${{ steps.sha.outputs.SHORT_SHA }}"' helm/values.yaml
      
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
      
      - name: Commit and push changes
        run: |
          git add helm/values.yaml
          git commit -m "chore: update image tag to ${{ steps.sha.outputs.SHORT_SHA }}"
          git push